"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first terms will be:
1, 2, 3, 5, 8, 13, 21, 34...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def even_fib_sum(limit):
    prev, curr = 1, 2
    sum = 0

    while curr < limit:
        if curr % 2 == 0:
            sum += curr
        prev, curr = curr, prev + curr
    
    return sum

print(even_fib_sum(4000000))